# CREATED USING EXTERNAL TWEAKER

recipes.removeShapeless(<survivalist:rock>);
recipes.addShaped(<improvedextraction:custom_cobblestone:3>, [[<improvedextraction:rock:4>, <improvedextraction:rock:4>], [<improvedextraction:rock:4>, <improvedextraction:rock:4>]]);
recipes.addShaped(<minecraft:clay_ball>, [[<survivalist:plant_fibres>, <survivalist:plant_fibres>, null], [null, <survivalist:plant_fibres>, null], [<survivalist:plant_fibres>, null, <survivalist:plant_fibres>]]);
recipes.addShaped(<extrautils2:redstoneclock>, [[<extrautils2:compressedcobblestone:1>, <minecraft:lever>, <extrautils2:compressedcobblestone:1>], [<minecraft:lever>, <minecraft:redstone_block>, <minecraft:lever>], [<extrautils2:compressedcobblestone:1>, <minecraft:lever>, <extrautils2:compressedcobblestone:1>]]);
recipes.addShaped(<openblocks:block_breaker>, [[<ore:cobblestone>, <ore:cobblestone>, <ore:cobblestone>], [<actuallyadditions:diamond_paxel>, <minecraft:lever>, <ore:cobblestone>], [<ore:cobblestone>, <ore:cobblestone>, <ore:cobblestone>]]);
recipes.addShaped(<tp:cobblegen_block>, [[<extrautils2:compressedcobblestone:1>, <extrautils2:compressedcobblestone:1>, <ore:compressed2xCobblestone>], [<minecraft:lava_bucket>, <minecraft:diamond_pickaxe>, <ore:listAllwater>], [<ore:compressed2xCobblestone>, <ore:compressed2xCobblestone>, <extrautils2:compressedcobblestone:1>]]);
recipes.addShaped(<extrautils2:pipe> * 8, [[<minecraft:stone_slab>, <minecraft:stone_slab>, <minecraft:stone_slab>], [<ore:ingotIron>, <ore:dustRedstone>, <ore:ingotIron>], [<minecraft:stone_slab>, <minecraft:stone_slab>, <minecraft:stone_slab>]]);
recipes.addShaped(<minecraft:bread>, [[<ore:cropWheat>, <minecraft:wheat>, <minecraft:wheat>], [<ore:cropWheat>, <minecraft:wheat>, <ore:cropWheat>]]);
recipes.addShaped(<extrautils2:teleporter:1>, [[<extrautils2:compressedcobblestone:3>, <ore:compressed2xCobblestone>, <extrautils2:compressedcobblestone:3>], [<ore:compressed2xCobblestone>, <ore:enderpearl>, <ore:compressed2xCobblestone>], [<extrautils2:compressedcobblestone:3>, <ore:compressed2xCobblestone>, <extrautils2:compressedcobblestone:3>]]);
recipes.addShaped(<minecraft:apple>, [[<survivalist:plant_fibres>, <survivalist:plant_fibres>, <survivalist:plant_fibres>], [<survivalist:plant_fibres>, null, <survivalist:plant_fibres>], [<survivalist:plant_fibres>, <survivalist:plant_fibres>, <survivalist:plant_fibres>]]);
recipes.addShaped(<minecraft:crafting_table>, [[<ore:plankWood>, <ore:plankWood>], [<ore:plankWood>, <ore:plankWood>]]);
recipes.addShaped(<minecraft:sapling>, [[<survivalist:plant_fibres>, <survivalist:plant_fibres>], [<survivalist:plant_fibres>, <survivalist:plant_fibres>]]);
recipes.addShaped(<extrautils2:teleporter:1>, [[<extrautils2:compressedcobblestone:3>, <ore:compressed2xCobblestone>, <extrautils2:compressedcobblestone:3>], [<ore:compressed2xCobblestone>, <minecraft:diamond>, <ore:compressed2xCobblestone>], [<extrautils2:compressedcobblestone:3>, <ore:compressed2xCobblestone>, <extrautils2:compressedcobblestone:3>]]);
recipes.remove(<extrautils2:redstoneclock>);
recipes.remove(<extrautils2:pipe> * 8);
recipes.remove(<minecraft:bread>);
recipes.remove(<extrautils2:teleporter:1>);
recipes.remove(<improvedextraction:ore_cluster:11>);
recipes.remove(<improvedextraction:ore_cluster:13>);
recipes.remove(<improvedextraction:ore_cluster:7>);
recipes.remove(<improvedextraction:ore_cluster:12>);
recipes.remove(<improvedextraction:ore_cluster:11>);
recipes.remove(<improvedextraction:ore_cluster:10>);
recipes.remove(<improvedextraction:ore_cluster:9>);
recipes.remove(<improvedextraction:ore_cluster:8>);
recipes.remove(<improvedextraction:ore_cluster:6>);
recipes.remove(<improvedextraction:ore_cluster:5>);
recipes.remove(<improvedextraction:ore_cluster:3>);
recipes.remove(<improvedextraction:ore_cluster:4>);
recipes.remove(<improvedextraction:ore_cluster:2>);
recipes.remove(<improvedextraction:ore_cluster:1>);
recipes.remove(<improvedextraction:ore_cluster>);
recipes.remove(<minecraft:flint>);
recipes.remove(<minecraft:flint>);
recipes.remove(<minecraft:wooden_hoe>);
recipes.remove(<minecraft:wooden_sword>);
recipes.remove(<minecraft:wooden_pickaxe>);
recipes.remove(<minecraft:wooden_axe>);
recipes.remove(<minecraft:wooden_shovel>);
recipes.remove(<minecraft:wooden_pickaxe>);
recipes.remove(<minecraft:crafting_table>);
recipes.remove(<minecraft:string>);
recipes.removeShaped(<improvedextraction:ore_cluster:12>, [[<improvedextraction:ore_fragment:12>, <improvedextraction:ore_fragment:12>], [<improvedextraction:ore_fragment:12>, <improvedextraction:ore_fragment:12>]]);
recipes.removeShaped(<improvedextraction:ore_cluster:3>, [[<improvedextraction:ore_fragment:3>]]);
recipes.removeShaped(<improvedextraction:ore_cluster:2>, [[<improvedextraction:ore_fragment>, <improvedextraction:ore_fragment>], [<improvedextraction:ore_fragment>, <improvedextraction:ore_fragment>]]);
recipes.addShapeless(<improvedextraction:ore_cluster:11>, [<improvedextraction:ore_fragment:11>, <improvedextraction:ore_fragment:11>, <improvedextraction:ore_fragment:11>, <improvedextraction:ore_fragment:11>]);
recipes.addShapeless(<improvedextraction:ore_cluster:12>, [<improvedextraction:ore_fragment:12>, <improvedextraction:ore_fragment:12>, <improvedextraction:ore_fragment:12>, <improvedextraction:ore_fragment:12>]);
recipes.addShapeless(<improvedextraction:ore_cluster:13>, [<improvedextraction:ore_fragment:13>, <improvedextraction:ore_fragment:13>, <improvedextraction:ore_fragment:13>, <improvedextraction:ore_fragment:13>]);
recipes.addShapeless(<improvedextraction:ore_cluster:10>, [<improvedextraction:ore_fragment:10>, <improvedextraction:ore_fragment:10>, <improvedextraction:ore_fragment:10>, <improvedextraction:ore_fragment:10>]);
recipes.addShapeless(<improvedextraction:ore_cluster:9>, [<improvedextraction:ore_fragment:9>, <improvedextraction:ore_fragment:9>, <improvedextraction:ore_fragment:9>, <improvedextraction:ore_fragment:9>]);
recipes.addShapeless(<improvedextraction:ore_cluster:8>, [<improvedextraction:ore_fragment:8>, <improvedextraction:ore_fragment:8>, <improvedextraction:ore_fragment:8>, <improvedextraction:ore_fragment:8>]);
recipes.addShapeless(<improvedextraction:ore_cluster:6>, [<improvedextraction:ore_fragment:6>, <improvedextraction:ore_fragment:6>, <improvedextraction:ore_fragment:6>, <improvedextraction:ore_fragment:6>]);
recipes.addShapeless(<improvedextraction:ore_cluster:5>, [<improvedextraction:ore_fragment:5>, <improvedextraction:ore_fragment:5>, <improvedextraction:ore_fragment:5>, <improvedextraction:ore_fragment:5>]);
recipes.addShapeless(<improvedextraction:ore_cluster:4>, [<improvedextraction:ore_fragment:4>, <improvedextraction:ore_fragment:4>, <improvedextraction:ore_fragment:4>, <improvedextraction:ore_fragment:4>]);
recipes.addShapeless(<improvedextraction:ore_cluster:3>, [<improvedextraction:ore_fragment:3>, <improvedextraction:ore_fragment:3>, <improvedextraction:ore_fragment:3>, <improvedextraction:ore_fragment:3>]);
recipes.addShapeless(<improvedextraction:ore_cluster:2>, [<improvedextraction:ore_fragment:2>, <improvedextraction:ore_fragment:2>, <improvedextraction:ore_fragment:2>, <improvedextraction:ore_fragment:2>]);
recipes.addShapeless(<improvedextraction:ore_cluster:1>, [<improvedextraction:ore_fragment:1>, <improvedextraction:ore_fragment:1>, <improvedextraction:ore_fragment:1>, <improvedextraction:ore_fragment:1>]);
recipes.addShapeless(<improvedextraction:ore_cluster>, [<improvedextraction:ore_fragment>, <improvedextraction:ore_fragment>, <improvedextraction:ore_fragment>, <improvedextraction:ore_fragment>]);
recipes.addShapeless(<minecraft:flint>, [<minecraft:gravel>]);
recipes.addShapeless(<improvedextraction:small_rock>, [<survivalist:plant_fibres>, <ore:plankWood>, <ore:plankWood>, <survivalist:plant_fibres>]);
recipes.remove(<tp:cobblegen_block>);
recipes.remove(<tp:bone_pickaxe>);
recipes.removeShaped(<minecraft:gravel>);
recipes.addShapeless(<minecraft:gravel>, [<extrautils2:compressedgravel>]);
recipes.remove(<tp:flint_axe>);
recipes.remove(<tp:flint_hoe>);
recipes.remove(<tp:flint_multi>);
recipes.remove(<tp:flint_spade>);
recipes.remove(<tp:flint_pickaxe>);
recipes.remove(<tp:flint_sword>);
recipes.addShaped(<extrautils2:miner>, [[<extrautils2:compressedcobblestone:1>, <extrautils2:compressedcobblestone:1>, <extrautils2:compressedcobblestone:1>], [<minecraft:redstone_block>, <minecraft:diamond_pickaxe>, <minecraft:redstone_block>], [<extrautils2:compressedcobblestone:1>, <extrautils2:compressedcobblestone:1>, <extrautils2:compressedcobblestone:1>]]);
mods.TinkerStages.addMaterialStage("wood&stoneblacklist", "wood");
mods.TinkerStages.addMaterialStage("wood&stoneblacklist", "stone");
recipes.addShapeless(<minecraft:string> * 2, [<survivalist:plant_fibres>, <survivalist:plant_fibres>, <survivalist:plant_fibres>]);
recipes.remove(<tconstruct:rack:1>.withTag({textureBlock: {id: "minecraft:wooden_slab", Count: 1 as byte, Damage: 0 as short}}));
recipes.addShaped(<improvedextraction:ore_cluster:7>, [[null, null, null],[null, <improvedextraction:ore_fragment:7>, <improvedextraction:ore_fragment:7>], [null, <improvedextraction:ore_fragment:7>, <improvedextraction:ore_fragment:7>]]);
recipes.remove(<teckle:blade>);
recipes.remove(<teckle:nikolite>);
recipes.remove(<teckle:siliconwafer>);
recipes.remove(<teckle:blueprint>);
recipes.remove(<teckle:alloyfurnace>);
recipes.remove(<teckle:beamquarry>);
recipes.remove(<teckle:filter>);
recipes.remove(<teckle:sortingmachine>);
recipes.remove(<industrialforegoing:range_addon:10>);
recipes.remove(<industrialforegoing:range_addon:11>);
recipes.addShaped(<teckle:tube.item> * 8, [[null, null, null],[<teckle:ingot>, <ore:glass>, <teckle:ingot>], [null, null, null]]);
recipes.addShaped(<teckle:filter>, [[<ore:cobblestone>, <ore:cobblestone>, <ore:cobblestone>],[<minecraft:gold_ingot>, <minecraft:piston>, <minecraft:gold_ingot>], [<ore:cobblestone>, <minecraft:redstone>, <ore:cobblestone>]]);
recipes.addShaped(<teckle:sortingmachine>, [[<minecraft:iron_ingot>, <minecraft:dye:4>, <minecraft:iron_ingot>],[<teckle:ingot:1>, <teckle:filter>, <teckle:ingot:1>], [<minecraft:iron_ingot>, <minecraft:redstone>, <minecraft:iron_ingot>]]);
recipes.addShaped(<industrialforegoing:range_addon:11>, [[<draconicevolution:draconium_ingot>, <industrialforegoing:plastic>, <draconicevolution:draconium_ingot>],[<draconicevolution:draconium_ingot>, <ore:paneGlass>, <draconicevolution:draconium_ingot>], [<draconicevolution:draconium_ingot>, <industrialforegoing:plastic>, <draconicevolution:draconium_ingot>]]);
recipes.addShaped(<industrialforegoing:range_addon:10>, [[<minecraft:emerald>, <industrialforegoing:plastic>, <minecraft:emerald>],[<minecraft:emerald>, <ore:paneGlassColorless>, <minecraft:emerald>], [<minecraft:emerald>, <industrialforegoing:plastic>, <minecraft:emerald>]]);
furnace.addRecipe(<mekanism:ingot:1>, <rebirth3contentmod:osmiumchunk>, 0.0);
furnace.addRecipe(<astralsorcery:itemcraftingcomponent:1>, <rebirth3contentmod:starmetalchunk>, 0.0);
furnace.remove(<astralsorcery:itemcraftingcomponent:1>, <astralsorcery:blockcustomore:1>);
recipes.remove(<excompressum:heavy_sieve>);
recipes.remove(<excompressum:heavy_sieve:1>);
recipes.remove(<excompressum:heavy_sieve:2>);
recipes.remove(<excompressum:heavy_sieve:3>);
recipes.remove(<excompressum:heavy_sieve:4>);
recipes.remove(<excompressum:heavy_sieve:5>);
recipes.remove(<excompressum:wooden_crucible>);
recipes.remove(<excompressum:wooden_crucible:5>);
recipes.remove(<excompressum:wooden_crucible:4>);
recipes.remove(<excompressum:wooden_crucible:3>);
recipes.remove(<excompressum:wooden_crucible:2>);
recipes.remove(<excompressum:wooden_crucible:1>);
recipes.remove(<excompressum:compressed_block:10>);
recipes.remove(<excompressum:compressed_block:9>);
recipes.remove(<excompressum:compressed_block:8>);
recipes.remove(<excompressum:compressed_block:6>);
recipes.remove(<excompressum:compressed_block:7>);
recipes.remove(<excompressum:compressed_block:5>);
recipes.remove(<excompressum:compressed_block:4>);
recipes.remove(<excompressum:compressed_block:3>);
recipes.remove(<excompressum:compressed_block:2>);
recipes.remove(<excompressum:compressed_block:1>);
recipes.remove(<exnihilocreatio:block_barrel0>);
recipes.remove(<exnihilocreatio:hammer_gold>);
recipes.remove(<exnihilocreatio:hammer_diamond>);
recipes.remove(<exnihilocreatio:hammer_iron>);
recipes.remove(<exnihilocreatio:hammer_stone>);
recipes.remove(<exnihilocreatio:hammer_wood>);
recipes.remove(<exnihilocreatio:item_material:1>);
recipes.remove(<exnihilocreatio:crook_bone>);
recipes.remove(<exnihilocreatio:item_mesh:1>);
recipes.remove(<exnihilocreatio:block_grinder>);
recipes.remove(<exnihilocreatio:block_axle_stone>);
recipes.remove(<exnihilocreatio:block_waterwheel>);
recipes.remove(<exnihilocreatio:block_auto_sifter>);
recipes.remove(<exnihilocreatio:block_sieve>);
recipes.addShaped(<exnihilocreatio:block_barrel0>, [[<ezwastelands:ezwastelandblock>, null, <ezwastelands:ezwastelandblock>],[<ezwastelands:ezwastelandblock>, null, <ezwastelands:ezwastelandblock>], [<ezwastelands:ezwastelandblock>, <ezwastelands:ezwastelandblock>, <ezwastelands:ezwastelandblock>]]);
recipes.addShaped(<skyresources:baseitemcomponent> * 3, [[null, <minecraft:wheat>, null],[<minecraft:wheat>, <minecraft:wheat>, <minecraft:wheat>], [null, <minecraft:wheat>, null]]);
recipes.addShaped(<skyresources:baseitemcomponent> * 3, [[null, <ore:cropApple>, null],[<ore:cropApple>, <ore:cropApple>, <ore:cropApple>], [null, <ore:cropApple>, null]]);
recipes.addShaped(<skyresources:baseitemcomponent> * 3, [[null, <ore:treeSapling>, null],[<ore:treeSapling>, <ore:treeSapling>, <ore:treeSapling>], [null, <ore:treeSapling>, null]]);
recipes.remove(<skyresources:baseitemcomponent:1>);
recipes.remove(<skyresources:baseitemcomponent:1>);
recipes.remove(<skyresources:cactuscuttingknife>);
recipes.remove(<skyresources:cactuscuttingknife>);
recipes.remove(<skyresources:ironcuttingknife>);
recipes.remove(<skyresources:diamondcuttingknife>);
recipes.remove(<skyresources:stonecuttingknife>);
recipes.remove(<skyresources:stonegrinder>);
recipes.remove(<skyresources:irongrinder>);
recipes.remove(<skyresources:diamondgrinder>);
recipes.remove(<skyresources:sandstoneinfusionstone>);
recipes.remove(<skyresources:redsandstoneinfusionstone>);
recipes.remove(<skyresources:alchemicalinfusionstone>);
recipes.remove(<skyresources:survivalistfishingrod>);
recipes.remove(<skyresources:fleshysnownugget>);
recipes.remove(<skyresources:cactusfruit>);
recipes.remove(<skyresources:heavyexplosivesnowball>);
recipes.remove(<skyresources:heavysnowball>);
recipes.remove(<skyresources:heatprovider:15>);
recipes.remove(<skyresources:heatprovider:14>);
recipes.remove(<skyresources:heatprovider:14>);
recipes.remove(<skyresources:heatprovider:15>);
recipes.remove(<skyresources:heatprovider:11>);
recipes.remove(<skyresources:heatprovider:10>);
recipes.remove(<skyresources:heatprovider:12>);
recipes.remove(<skyresources:heatprovider:13>);
recipes.remove(<skyresources:heatprovider:8>);
recipes.remove(<skyresources:heatprovider:9>);
recipes.remove(<skyresources:heatprovider:7>);
recipes.remove(<skyresources:heatprovider:6>);
recipes.remove(<skyresources:heatprovider:6>);
recipes.remove(<skyresources:heatprovider:5>);
recipes.remove(<skyresources:heatprovider:4>);
recipes.remove(<skyresources:heatprovider:3>);
recipes.remove(<skyresources:heatprovider:2>);
recipes.remove(<skyresources:heatprovider:1>);
recipes.remove(<skyresources:heatprovider>);
recipes.remove(<skyresources:combustionheater:15>);
recipes.remove(<skyresources:combustionheater:14>);
recipes.remove(<skyresources:combustionheater:13>);
recipes.remove(<skyresources:combustionheater:12>);
recipes.remove(<skyresources:combustionheater:11>);
recipes.remove(<skyresources:combustionheater:10>);
recipes.remove(<skyresources:combustionheater:9>);
recipes.remove(<skyresources:combustionheater:10>);
recipes.remove(<skyresources:combustionheater:11>);
recipes.remove(<skyresources:combustionheater:8>);
recipes.remove(<skyresources:combustionheater:7>);
recipes.remove(<skyresources:combustionheater:6>);
recipes.remove(<skyresources:combustionheater:5>);
recipes.remove(<skyresources:combustionheater:4>);
recipes.remove(<skyresources:combustionheater:3>);
recipes.remove(<skyresources:combustionheater:1>);
recipes.remove(<skyresources:combustionheater>);
recipes.remove(<skyresources:techitemcomponent>);
recipes.remove(<skyresources:baseitemcomponent:5>);
recipes.remove(<skyresources:baseitemcomponent:4>);
recipes.remove(<skyresources:baseitemcomponent:1>);
recipes.remove(<skyresources:baseitemcomponent:2>);
recipes.remove(<skyresources:baseitemcomponent:3>);
recipes.remove(<skyresources:alchemy:13>);
recipes.remove(<skyresources:alchemy:12>);
recipes.remove(<skyresources:heat:12>);
recipes.remove(<skyresources:heat:15>);
recipes.remove(<skyresources:heat:14>);
recipes.remove(<skyresources:heat:13>);
recipes.remove(<skyresources:heat:11>);
recipes.remove(<skyresources:heat:10>);
recipes.remove(<skyresources:heat:9>);
recipes.remove(<skyresources:heat:8>);
recipes.remove(<skyresources:heat:7>);
recipes.remove(<skyresources:heat:5>);
recipes.remove(<skyresources:heat:6>);
recipes.remove(<skyresources:heat:4>);
recipes.remove(<skyresources:heat:3>);
recipes.remove(<skyresources:heat:2>);
recipes.remove(<skyresources:heat:1>);
recipes.remove(<skyresources:heat>);
recipes.remove(<skyresources:alchemyitemcomponent:9>);
recipes.remove(<skyresources:alchemyitemcomponent:10>);
recipes.remove(<skyresources:drycactus>);
recipes.remove(<skyresources:silverfishdisruptor>);
recipes.remove(<skyresources:dirtfurnace>);
recipes.remove(<skyresources:aqueousdeconcentrator>);
recipes.remove(<skyresources:aqueousconcentrator>);
recipes.remove(<skyresources:wildlifeattractor>);
recipes.remove(<skyresources:lightfreezer>);
recipes.remove(<skyresources:ironfreezer>);
recipes.remove(<skyresources:minifreezer>);
recipes.remove(<skyresources:lifeinjector>);
recipes.remove(<skyresources:lifeinfuser>);
recipes.remove(<skyresources:combustioncontroller>);
recipes.remove(<skyresources:quickdropper>);
recipes.remove(<skyresources:rockcleaner>);
recipes.remove(<skyresources:combustioncollector>);
recipes.remove(<skyresources:rockcrusher>);
recipes.remove(<skyresources:heavysnow>);
recipes.remove(<skyresources:magmafiedstone>);
recipes.remove(<skyresources:petrifiedplanks>);
recipes.remove(<skyresources:petrifiedwood>);
recipes.remove(<skyresources:blazepowderblock>);
recipes.remove(<skyresources:coalinfusedblock>);
recipes.remove(<skyresources:sandynetherrack>);
recipes.remove(<skyresources:lightmatterblock>);
recipes.remove(<skyresources:darkmatterblock>);
recipes.remove(<skyresources:compressedcoalblock>);
recipes.remove(<skyresources:cactusfruitneedle>);
recipes.addShapeless(<skyresources:techitemcomponent:1> * 6, [<minecraft:gunpowder>,<minecraft:gunpowder>,<minecraft:gunpowder>,<minecraft:gunpowder>,<minecraft:spider_eye>,<minecraft:spider_eye>,<minecraft:poisonous_potato>]);
recipes.addShapeless(<skyresources:alchemyitemcomponent:2> * 3, [<minecraft:gunpowder>,<minecraft:gunpowder>,<minecraft:blaze_powder>,<minecraft:gunpowder>,<minecraft:blaze_powder>,<ore:itemCoal>]);
recipes.addShaped(<skyresources:techitemcomponent:2>, [[<minecraft:ice>, <minecraft:ice>, <minecraft:ice>],[<minecraft:ice>, <minecraft:iron_ingot>, <minecraft:ice>], [<minecraft:ice>, <minecraft:ice>, <minecraft:ice>]]);
recipes.addShaped(<magneticraft:ingots:5>, [[<ore:dyeBlack>, <ore:dyeBlack>, <ore:dyeBlack>],[<ore:dyeBlack>, <ore:ingotOsmium>, <ore:dyeBlack>], [<ore:dyeBlack>, <ore:dyeBlack>, <ore:dyeBlack>]]);
recipes.addShaped(<integrateddynamics:menril_sapling>, [[<minecraft:dye:4>, <minecraft:dye:4>, <minecraft:dye:4>],[<minecraft:dye:4>, <ore:treeSapling>, <minecraft:dye:4>], [<minecraft:dye:4>, <minecraft:dye:4>, <minecraft:dye:4>]]);
recipes.remove(<actuallyadditions:block_giant_chest>);
recipes.addShapeless(<rebirth3contentmod:osmiumchunk>, [<rebirth3contentmod:osmiumshard>,<rebirth3contentmod:osmiumshard>,<rebirth3contentmod:osmiumshard>,<rebirth3contentmod:osmiumshard>]);
recipes.addShapeless(<rebirth3contentmod:starmetalchunk>, [<rebirth3contentmod:starmetalshard>,<rebirth3contentmod:starmetalshard>,<rebirth3contentmod:starmetalshard>,<rebirth3contentmod:starmetalshard>]);
recipes.addShapeless(<survivalist:plant_fibres>, [<ezwastelands:ezwastelandblock>,<ezwastelands:ezwastelandblock>,<ezwastelands:ezwastelandblock>,<ezwastelands:ezwastelandblock>]);